### ISSUE TITLE
EPIC: SciCat integration

### ISSUE THREAD

**Issue by rozyczko** [EasyScience/EasyDiffractionLib#19]
Epic to track progress of features:

- [ ] https://github.com/EasyScience/EasyDiffractionLib/issues/20
- [ ] https://github.com/EasyScience/EasyDiffractionLib/issues/21
- [ ] https://github.com/EasyScience/EasyDiffractionLib/issues/22
- [ ] https://github.com/EasyScience/EasyDiffractionLib/issues/23

**Comment by rozyczko** [comment]
API to use: https://github.com/SciCatProject/pyscicat
